#!/bin/bash

[ -z $1 ] && echo -e "Command Syntax: splitter file.mp3 timestamps_file\nTimestamp Syntax: 00:00:00-Artist-Title" && exit

inputaudio=$1
list="$2"

timestamps=( $(cut -d'-' -f1 $list) )
length=${#timestamps[@]}

titles=( $(cut -d'-' -f3 $list | sed 's/\ /_/g') )
artists=( $(cut -d'-' -f2 $list | sed 's/\ /_/g') )

last_song_timestamp=${timestamps[$length-1]}

echo "There are $length timestamps"

folder="$(echo "$inputaudio" | iconv -c -f UTF-8 -t ASCII//TRANSLIT | tr -d '[:punct:]' | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sed "s/-\+/-/g;s/\(^-\|-\$\)//g")"
! mkdir -p "$folder" && echo "Do you have write access in this directory?" && exit 1

for (( i=0; i<$length-1; i++))
  do
    artist=$(echo ${artists[$i]} | sed 's/_/\ /g')
    title=$(echo ${titles[$i]} | sed 's/_/\ /g')
    file="$artist - $title.mp3"
    begin=${timestamps[$i]}
    end=${timestamps[$i+1]}
    echo -e "$begin => $end \t ARTIST: $artist \t TITLE: $title"
   	ffmpeg -nostdin -y -loglevel -8 -i "$inputaudio" -ss "$begin" -to "$end" -vn -c copy -metadata title="$title" -metadata artist="$artist" "$folder/$file"
  done

##exporting last song
artist=$(echo ${artists[$length-1]} | sed 's/_/\ /g')
title=$(echo ${titles[$length-1]} | sed 's/_/\ /g')
file="$artist - $title.mp3"
begin=${timestamps[$length-1]}
end="END"
echo -e "$begin => $end \t ARTIST: $artist \t TITLE: $title"
ffmpeg -nostdin -y -loglevel -8 -i "$inputaudio" -ss "$begin" -vn -c copy -metadata title="$title" -metadata artist="$artist" "$folder/$file"
echo "done"
